package jp.co.waja.core.model;

public enum Permission {
	SHOW_MY_PROFILE,
	EDIT_MY_PASSWORD,

	LIST_MY_WORK_TIME,
	COMPLETE_MY_WORK_TIME,
	EDIT_MY_WORK_TIME,
	BULK_EDIT_MY_WORK_TIME,

	LIST_TEAM_STAFF,
	DESCRIBE_TEAM_STAFF,
	LIST_TEAM_WORK_TIME,
	APPROVE_TEAM_WORK_TIME,

	LIST_ALL_STAFF,
	CREATE_ALL_STAFF,
	DESCRIBE_ALL_STAFF,
	EDIT_ALL_STAFF,
	DELETE_ALL_STAFF,
	LIST_ALL_WORK_TIME,
	APPROVE_ALL_WORK_TIME,
	EDIT_ALL_WORK_TIME,

	CREATE_ALL_LONG_VACATION,
	DELETE_ALL_LONG_VACATION,

	LIST_ALL_TEAM,
	CREATE_ALL_TEAM,
	EDIT_ALL_TEAM,
	DELETE_ALL_TEAM
}
